// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1261.RoboLions2015.subsystems;

import org.usfirst.frc1261.RoboLions2015.RobotMap;
import org.usfirst.frc1261.RoboLions2015.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder leftEncoder = RobotMap.driveTrainLeftEncoder;
    Encoder rightEncoder = RobotMap.driveTrainRightEncoder;
    Gyro gyro = RobotMap.driveTrainGyro;
    Ultrasonic ultrasonic = RobotMap.driveTrainUltrasonic;
    SpeedController leftDrive1 = RobotMap.driveTrainLeftDrive1;
    SpeedController leftDrive2 = RobotMap.driveTrainLeftDrive2;
    SpeedController rightDrive1 = RobotMap.driveTrainRightDrive1;
    SpeedController rightDrive2 = RobotMap.driveTrainRightDrive2;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public double getDistance() {
    	double averagePulses = (leftEncoder.getDistance() - rightEncoder.getDistance()/2);
    	int pulsesPerRotation = 360; // In Degrees
    	int diameter = 6; // In inches
    	double distance = (averagePulses/pulsesPerRotation) * diameter * Math.PI;
    	return distance;
    }
    
    public RobotDrive getRobotDrive() {
    	return robotDrive;
    }
    
    public double distanceTraveled() {
    	return (leftEncoder.getDistance() - rightEncoder.getDistance()) /2;
    }
    
    public void resetDistance() {
    	leftEncoder.reset();
    	rightEncoder.reset();
    }
    
    public RobotDrive getRobotDrive1() {
    	return robotDrive;
    }
    
    public SpeedController getLeftDrive() {
    	return leftDrive1;
    }
    
    public SpeedController getRightDrive() {
    	return rightDrive1;
    }
    
    public Encoder getLeftEncoder() {
    	return leftEncoder;
    }
    
    public Encoder getRightEncoder() {
    	return rightEncoder;
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveWithJoysticks());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
}

